version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgweb:
    image: sosedoff/pgweb
    restart: always # optional
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres # my database container is called postgres, not db

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "./stack/nginx.conf:/etc/nginx/conf.d/default.conf"
    command: ["nginx", "-g", "daemon off;"]
