version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgweb:
    image: sosedoff/pgweb
    restart: always  # optional
    network_mode: host
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/postgres
    depends_on:
      - postgres  # my database container is called postgres, not db

  nginx:
    image: nginx:stable
    restart: always
    network_mode: host
    volumes:
      - './stack/nginx.conf:/etc/nginx/conf.d/default.conf'
    command: ["nginx", "-g", "daemon off;"]